### ISSUE TITLE
Flash & Configure loaner limelight

### ISSUE THREAD

**Issue by legoguy1000** [Frc5572/FRC2022#146]
The Grease Monkeys loaned us their limelight as a spare during the Austin event.  IDK if we're holding onto it for a while but if so, we should flash it and configure it as a proper backup. We won't do anything until we figure out the plan for it.

**Comment by legoguy1000** [comment]
this is done correct??

**Comment by aidund** [comment]
> this is done correct??

Yes, it is finished.
