### ISSUE TITLE
Hood subsystem

### ISSUE THREAD

**Issue by agrinmanriv0537** [Frc5572/FRC2022#26]

**Comment by legoguy1000** [comment]
Learned from Russell that the rotational servo is not like the linear servo. It goes from 0 to 360 and then just restarts so it's essentially a motor connected directly to the roboRio. Russell said they're point a CANcoder on it so we'll have exact amount of rotation so we'll have to see how that works. It may play well into the `isFinished` function to stop the command.

**Comment by legoguy1000** [comment]
Hood is going to be a fixed hood.
