### ISSUE TITLE
Is there ever a time when we will need to run both inside and outside climbers at the same time?

### ISSUE THREAD

**Issue by legoguy1000** [Frc5572/FRC2022#47]
Is there ever a time when we will need to run both inside and outside climbers at the same time? With different commands. We may need to split this into separate subsystems later or make new commands that include both sets of motors.

_Originally posted by @legoguy1000 in https://github.com/Frc5572/FRC2022/pull/29#r799052909_

**Comment by aidund** [comment]
According to Rusinski, no, we would always be using separate climbers (e.g., outside climbers to initially go up to first bar, inside to move to next bar, outside to move to final bar, etc.)
