### ISSUE TITLE
Add LEDs

### ISSUE THREAD

**Issue by agrinmanriv0537** [Frc5572/FRC2022#60]
- [ ] Locked on to target with ball (green)
- [ ] Ball loaded (blue)
- [x] Ready to climb (linked to start button on driver) (rainbow)
- [ ] Button operator for police lights
- [ ] locked on to target with no ball (red)

**Comment by aidund** [comment]
this sounds awesome great idea alex

**Comment by legoguy1000** [comment]
> this sounds awesome great idea alex

It was Hector's want

**Comment by aidund** [comment]
waiting until we get a new rev blinker (if we do, thanks resnick)

**Comment by legoguy1000** [comment]
Moved to State Champs

**Comment by legoguy1000** [comment]
I ordered some extra cables for the LEDs, once we get them we can connect directly to the Rio via PWM and not need a CANdle or Blinkin.
